server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME} 
 
spring:
  application:
    name: spring-gateway  cloud:    gateway:      routes:      - id: springAuth
        uri: lb://SPRING-AUTH
        predicates:
        - Path=/spring-auth/*** 

