spring:
  application:
    name: spring-auth
server:
  servlet:
    context-path: /spring-auth
  port: 8661
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 
    hostname: ${COMPUTERNAME}